services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
      - path: .env.docker
        required: false
    environment:
      DB_DATABASE: /var/lib/mt5-database/database.sqlite
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ${DOCKER_SOCKET_HOST:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - app-storage:/var/www/html/storage
      - app-database:/var/lib/mt5-database
      - app-config:/var/lib/mt5-config
    restart: unless-stopped

volumes:
  app-storage:
  app-database:
  app-config: